app/__init__.py
from flask import Flask, render_template
from config import Config
from .api.routes import api
from .authentication.routes import auth
from .site.routes import site
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.join_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, render_template, jsonify, request
from helpers import token_required
from models import Photo, Meme, photo_schema, all_photo_schemas, meme_schema, all_meme_schemas, db, User

api = Blueprint("api", __name__, url_prefix="/api")

@api.route("/data")
def data():
    return jsonify({"Minecraft": "is great"})

@api.route("/photos", methods = ["POST"])
@token_required
def addphoto(your_token):
    name = request.json["name"]
    link = request.json["link"]
    user_token = your_token.token

    print(f"BIG TESTER: {your_token}")

    photo = Photo(name, link, user_token = user_token)
    
    db.session.add(photo)
    db.session.commit()

    response = photo_schema.dump(photo)
    return jsonify(response)

@api.route("/photos", methods = ["GET"])
@token_required
def displayallphotos(your_token):
    owner = your_token.token
    photos = Photo.query.filter_by(user_token = owner).all()
    response = all_photo_schemas.dump(photos)
    return jsonify(response)

@api.route("/photos/<id>", methods = ["GET"])
@token_required
def displayphotos(your_token, id):
    owner = your_token.token
    if owner == your_token.token:
        photo = Photo.query.get(id)
        response = photo_schema.dump(photo)
        return jsonify(response)
    else:
        return jsonify({"ERROR": "Sorry, valid token required"}), 401

@api.route("/photos/<id>", methods = ["PUT", "POST"])
@token_required
def updatephoto(your_token, id):
    photo = Photo.query.get(id)
    photo.name = request.json["name"]
    photo.link = request.json["link"]
    photo.user_token = your_token.token

    db.session.commit()
    response = photo_schema.dump(photo)
    return jsonify(response)

@api.route("/photos/<id>", methods = ["DELETE"])
@token_required
def deletephoto(your_token, id):
    photo = Photo.query.get(id)
    db.session.delete(photo)
    db.session.commit()
    response = photo_schema.dump(photo)
    return jsonify(response)

@api.route("/memes", methods = ["POST"])
@token_required
def creatememe(your_token):
    title = request.json["title"]
    caption = request.json["caption"]
    photo_id = request.json["photo_id"]
    user_token = your_token.token

    meme = Meme(title, caption, photo_id, user_token = user_token)

    db.session.add(meme)
    db.session.commit()

    response = meme_schema.dump(meme)
    return jsonify(response)

@api.route("/memes", methods = ["GET"])
@token_required
def viewallmemes(your_token):
    owner = your_token.token
    memes = Meme.query.filter_by(user_token = owner).all()
    response = all_meme_schemas.dump(memes)
    return jsonify(response)

@api.route("/memes/<id>", methods = ["GET"])
@token_required
def viewmeme(your_token, id):
    owner = your_token.token

    if owner == your_token.token:
        memes = Meme.query.get(id)
        response = meme_schema.dump(memes)
        return jsonify(response)
    else:
        return jsonify({"ERROR": "Sorry, valid token required"}), 41

@api.route("/memes/<id>", methods = ["PUT", "POST"])
@token_required
def editmeme(your_token, id):
    meme = Meme.query.get(id)

    meme.title = request.json["title"]
    meme.caption = request.json["caption"]
    meme.photo_id = request.json["photo_id"]
    meme.user_token = your_token.token

    db.session.commit()

    response = meme_schema.dump(meme)
    return jsonify(response)

@api.route("/memes/<id>", methods = ["DELETE"])
@token_required
def deletememe(your_token, id):
    meme = Meme.query.get(id)
    db.session.delete(meme)
    db.session.commit()
    response = meme_schema.dump(meme)
    return jsonify(response)

app/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, LoginManager, current_user, login_required
from models import User, db, check_password_hash
from forms import CreateNewAccount, LoginAccount

auth = Blueprint("auth", __name__, template_folder="auth_templates")

@auth.route("/signup", methods = ["GET", "POST"])
def signup():
    form = CreateNewAccount()

    try:
        if request.method == "POST" and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            username = form.username.data
            email = form.email.data
            password = form.password.data
            print(first_name, last_name, username, email, password)
            
            user = User(first_name, last_name, username, email, password=password)

            db.session.add(user)
            db.session.commit()

            print(f"You have successfully created a new account. Welcome {username} to the memes :)")
            flash(f"You have successfully created a new account. Welcome {username} to the memes :)")
            return redirect(url_for("site.welcome"))
    except:
        print("Sorry, invalid form data")
        raise Exception("Sorry, invalid form data")
    
    return render_template("sign_up.html", form=form)

@auth.route("/signin", methods = ["GET", "POST"])
def signin():
    form = LoginAccount()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash("You are successfully logged in.")
                return redirect(url_for("site.home"))
            else:
                flash("Access Denied")
    except:
        raise Exception("Sorry invalid form data")
    
    return render_template("sign_in.html", form=form)

@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("site.logoff"))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint("site", __name__, template_folder="site_templates")

@site.route("/")
def welcome():
    return render_template("welcome.html")

@site.route("/home")
def home():
    return render_template("home.html")

@site.route("/profile")
def profile():
    return render_template("profile.html")

@site.route("/logoff")
def logoff():
    return render_template("logged_out.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<title>MEMES</title>
</head>
<body class="bg-warning">
    <nav class="bg-dark text-light text-center align-items-center d-flex flex-row justify-content-between">
        <div class="bg-dark m-2 ms-3 p-0 d-flex flex-row justify-content-center">
            <h1 class="text-danger m-0 p-0">M</h1>
            <h1 class="text-warning m-0 p-0">E</h1>
            <h1 class="text-success m-0 p-0">M</h1>
            <h1 class="text-primary m-0 p-0">E</h1>
            <h1 class="text-info m-0 p-0">S</h1>
        </div>
        <div class="bg-dark m-2 p-0 d-flex flex-row justify-content-center">
            <a href="{{ url_for('site.home')}}" class="text-decoration-none me-3"><h5 class="text-light">Home</h5></a>
            <a href="{{ url_for('site.profile')}}" class="text-decoration-none me-3"><h5 class="text-light">Profile</h5></a>
            <a href="{{ url_for('site.logoff')}}" class="text-decoration-none me-3"><h5 class="text-light">Log-out</h5></a>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/signin_forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <div>
            {{ form.email.label }}
            {{ form.email(class="form-control")}}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password(class="form-control")}}
        </div>
    </fieldset>
    {{ form.submit_button(class="fw-bold btn btn-dark align-items-center text-light m-2")}}
</form>

app/templates/signup_forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <div>
            {{ form.first_name.label }}
            {{ form.first_name(class="form-control")}}
        </div>
        <div>
            {{ form.last_name.label }}
            {{ form.last_name(class="form-control")}}
        </div>
        <div>
            {{ form.username.label }}
            {{ form.username(class="form-control")}}
        </div>
        <div>
            {{ form.email.label }}
            {{ form.email(class="form-control")}}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password(class="form-control")}}
        </div>
    </fieldset>
    {{ form.submit_button(class="fw-bold btn btn-dark align-items-center text-light m-2")}}
</form>